"""add page_number and metadata to chunks

Revision ID: 4f205b777ee3
Revises: 90aa12f326f4
Create Date: 2026-06-21 19:04:58.575838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f205b777ee3'
down_revision: Union[str, None] = '90aa12f326f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'metadata')
    op.drop_column('chunks', 'page_number')
    # ### end Alembic commands ###
