"""initial schema

Revision ID: 90aa12f326f4
Revises: 
Create Date: 2026-06-21 18:30:55.304379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90aa12f326f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_chunks_tenant_id'), 'chunks', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'chunks', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_index(op.f('ix_chunks_tenant_id'), table_name='chunks')
    op.drop_column('chunks', 'tenant_id')
    # ### end Alembic commands ###
